$(function(){
$("#img1").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img2").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img3").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img4").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img5").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img6").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img7").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img8").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img9").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img10").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img11").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img12").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img13").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img14").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img15").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img16").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img17").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img18").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img19").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img20").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img21").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img22").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img23").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img24").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img25").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img26").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img27").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img1").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});$(function(){
$("#img28").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img1").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img29").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img30").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img31").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img32").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img33").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img34").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});
$(function(){
$("#img35").hover(function(){
$(this).attr("src","../graphics/placeholder.png");
},function(){
$(this).attr("src","../graphics/placeholder.png");
});
});